2026.03.12 : 전처리

In [21]:
import pandas as pd

In [22]:
# 결측치 처리 
data={
    'Name': ['Alice', 'Bob', None],
    'Age': [25, None, 30],
    'Score': [85, 90, None]
    }
df = pd.DataFrame(data)

In [23]:
df.info()
# 결측치 확인
df.isnull()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      float64
 2   Score   2 non-null      float64
dtypes: float64(2), str(1)
memory usage: 204.0 bytes

    Name    Age  Score
0  False  False  False
1  False   True  False
2   True  False   True

In [24]:
# 결측치가 있는 행을 삭제
df_missing_rows = df.dropna()
print(df_missing_rows)

    Name   Age  Score
0  Alice  25.0   85.0

In [34]:
# 결측치가 있는 열을 삭제
df_missing_cols = df.dropna(axis=1)
print(df_missing_cols)

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  27.5   90.0
2  Alice  30.0   87.5

In [ ]:
# 결측치에 특정값으로 대체

# 나이값을 평균값으로 대체
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 점수값을 중간값으로 대체
df['Score'] = df['Score'].fillna(df['Score'].median())

# 이름값을 최빈값으로 대체
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])

df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  27.5   90.0
2  Alice  30.0   87.5

In [39]:
#이상치 처리
data = {
    'score' : [70, 75, 80, 85, 90, 150]
}

df = pd.DataFrame(data)
df

   score
0     70
1     75
2     80
3     85
4     90
5    150

In [41]:
#IQP
Q1 = df['score'].quantile(0.25)
Q3 = df['score'].quantile(0.75)
IQR = Q3-Q1
print(Q1, Q3, IQR)

76.25 88.75 12.5

In [43]:
low_ = Q1 - (1.5 * IQR)
up_ = Q3 + (1.5 * IQR)
print(f'이상치의 범위 {low_}보다 작은값, {up_}보다 큰값')

이상치의 범위 57.5보다 작은값, 107.5보다 큰값

In [48]:
# 이상치 값 찾기 
df_1 = df[ (df['score']<low_) | (df['score']>up_) ]
df_1

   score
5    150

In [50]:
# 이상치를 제거한 데이터
df_2 = df[(df['score']>=low_) & (df['score']<=up_)]
df_2

   score
0     70
1     75
2     80
3     85
4     90

In [55]:
# 이상치 데이터를 변경
df['score'] = df['score'].astype(float)
df.loc[df['score'] < low_, 'score'] = low_
df.loc[df['score']>up_, 'score'] = up_
df

   score
0   70.0
1   75.0
2   80.0
3   85.0
4   90.0
5  107.5

In [59]:
# 중복 데이터 처리 : 확인 -> 
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'Score': [85, 90, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [69]:
# 중복찾기
df.duplicated()

# 중복된 행의 개수
df.duplicated().sum()

# 특정 열의 값을 기준으로 중복 체크
df.duplicated(subset=['Name']).sum()

# 중복된 행을 추출
df[df.duplicated()]

    Name  Age  Score
2  Alice   25     85
4    Bob   30     90

In [71]:
# 중복된 행을 삭제
df_clearned = df.drop_duplicates()
df_clearned

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95

In [74]:
df_clearned2 = df.drop_duplicates(keep='last')
df_clearned2

      Name  Age  Score
2    Alice   25     85
3  Charlie   35     95
4      Bob   30     90

In [76]:
df_clearned3 = df.drop_duplicates(subset=['Name'])
df_clearned3

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
3  Charlie   35     95

In [78]:
df_clearned4 = df.drop_duplicates(keep=False)
df_clearned4

      Name  Age  Score
3  Charlie   35     95

In [80]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\sk_shieldus_rookies\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\sk_shieldus_rookies\.venv\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\sk_shieldus_rookies\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\sk_shieldus_rookies\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\sk_shieldus_rookies\.venv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [81]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

In [83]:
data1 = pd.DataFrame(
    {
        'original' : [50, 80, 90, 100, 160]
    }
    )
data2 = pd.DataFrame(
    {
        'Fruits' : ['사과', '배', '포도', '사과', '포도']
    }
)

In [ ]:
# 표준화
scaler_1 = StandardScaler()
data1['scale_1'] = scaler_1.fit_transform(data1[['original']])

# 정규화
scaler_2 = MinMaxScaler()
data1['scaled_2'] = scaler_2.fit_transform(data1[['original']])
data1

   original   scale_1  scaled_2
0        50 -1.273852  0.000000
1        80 -0.443079  0.272727
2        90 -0.166155  0.363636
3       100  0.110770  0.454545
4       160  1.772316  1.000000

In [90]:
encoder_1 = LabelEncoder()
data2['Label Encoding'] = encoder_1.fit_transform(data2['Fruits'])

data2

  Fruits  Label Encoding
0     사과               1
1      배               0
2     포도               2
3     사과               1
4     포도               2