2026.03.09
클래스의 상속

In [1]:
# 사칙연산을 하는 클래스 : 클래스이름, 변수, 함수, 초기화 함수
# 클래스 이름 : 대문자로 시작 => FourCal
# 변수 : 숫자 두개
# 함수(메서드) : +, -, *, /

class FourCal:
    # 클래스의 멤버 : 변수, 함수

    # 변수 초기화 => 초기화 함수
    def __init__(self, first, second):
        self.first=first
        self.second=second

    # 함수
    # 클래스에서 함수를 사용할 때는 반드시 self 매개변수를 사용
    # self -> 실행 시점점의 함수를 포함하는 객체 자신을 가르키는 변수
    def setData(self, first, second):
        self.first = first
        self.second = second

    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second

In [10]:
# 클래스의 상속 : 새로운 클래스를 생성
# 기존의 클래스의 맴버(변수, 메서드)들을 받아서 새로운 클래스를 생성
# 오버라이딩 : 메서드를 수정(처리블럭)해서 사용
# MoreFourCal : 새로운 클래스 정의 => pow  제곱 구해주는 함수, div 메서드를 수정
class MoreFourCal(FourCal):
    #pass
    def pow(self):
        return self.first**self.second
    
    # 오버라이딩 : 함수의 이름과 매개변수는 그대로 하고 처리부분을 수정해서 정의
    def div(self):
        if self.second == 0 :
            return 0
        return self.first/self.second

In [11]:
mfc1 = MoreFourCal(10, 0)

In [12]:
#mfc1.pow()
mfc1.div()

0

모듈

In [14]:
import mod.mod2

mod2 실행 시작
mode2 실행 끝

표준모듈

In [3]:
import datetime

In [5]:
day1 = datetime.date(2026,1,25)
print(day1, type(day1))

2026-01-25 <class 'datetime.date'>

In [6]:
day2 = datetime.date(2026, 1, 1)

In [8]:
print(day1-day2)

24 days, 0:00:00

In [10]:
print(day1.year, day1.month, day1.day)

2026 1 25

In [11]:
import time

In [12]:
time.time()

1773032268.548434

In [14]:
lt = time.localtime()

In [19]:
print(lt.tm_year, lt.tm_mon, lt.tm_mday)

2026 3 9

In [20]:
time.ctime()

'Mon Mar  9 14:02:56 2026'

In [21]:
import random as r

In [35]:
r.random()   # 0이상 1미만의 실수를 반환

0.7770197883720852

In [67]:
int(r.random()*10)

6

In [109]:
r.randint(1,46)

19

In [112]:
list_score = []
for s in range(0,10):
    list_score.append(r.randint(60, 100))
print(list_score)

[100, 74, 73, 65, 76, 74, 91, 94, 88, 95]

In [126]:
r.choice(list_score)

76

In [137]:
r.sample(list_score, 5)

[91, 94, 73, 100, 74]

In [138]:
import os

In [139]:
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\LG\\AppData\\Roaming',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_17176_JPDCUKBXFQFOFELM',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-9N5PTRO',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'EFC_11560_1262719628': '1',
        'EFC_11560_1592913036': '1',
        'EFC_11560_2283032206': '1',
        'EFC_11560_2775293581': '1',
        'EFC_11560_3789132940': '1',
        'ELECTRON_RUN_AS_NODE': '1',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\LG',
        'JPY_INTERRUPT_EVENT': '2204',
        'LANG': 'KO',
        'LEVEL_ZERO_V1_SDK_PATH': 'C:\\Program Files\\LevelZeroSDK\\1.23.1\\',
        'LOCALAPPDATA': 'C:\\Users\\LG\\AppData\\Local',
        'LOGONSERVER': '\\\\DESKTOP-9N5PTRO',
        'NUMBER_OF_PROCESSORS': '12',
        'ONEDRIVE': 'C:\\Users\\LG\\OneDrive',
        'OS': 'Windows_NT',
        'PATH': 'c:\\python_proj\\.venv\\Scripts;C:\\Users\\LG\\AppData\\Local\\Programs\\Microsoft VS Code;C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\util;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\NetSarang\\Xshell 8\\;C:\\Program Files (x86)\\NetSarang\\Xshell 7\\;C:\\Program Files\\Bandizip\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Git\\cmd;C:\\Users\\LG\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\LG\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\LG\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\LG\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;',
        'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        'PROCESSOR_ARCHITECTURE': 'AMD64',
        'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 186 Stepping 3, GenuineIntel',
        'PROCESSOR_LEVEL': '6',
        'PROCESSOR_REVISION': 'ba03',
        'PROGRAMDATA': 'C:\\ProgramData',
        'PROGRAMFILES': 'C:\\Program Files',
        'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
        'PROGRAMW6432': 'C:\\Program Files',
        'PROMPT': '(.venv) $P$G',
        'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
        'PUBLIC': 'C:\\Users\\Public',
        'PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING': '1',
        'PYTHONIOENCODING': 'utf-8',
        'PYTHONUNBUFFERED': '1',
        'PYTHON_FROZEN_MODULES': 'on',
        'SESSIONNAME': 'Console',
        'SYSTEMDRIVE': 'C:',
        'SYSTEMROOT': 'C:\\WINDOWS',
        'TEMP': 'C:\\Users\\LG\\AppData\\Local\\Temp',
        'TMP': 'C:\\Users\\LG\\AppData\\Local\\Temp',
        'USERDOMAIN': 'DESKTOP-9N5PTRO',
        'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-9N5PTRO',
        'USERNAME': 'LG',
        'USERPROFILE': 'C:\\Users\\LG',
        'VIRTUAL_ENV': 'c:\\python_proj\\.venv',
        'VIRTUAL_ENV_PROMPT': '(.venv) ',
        'VSCODE_CODE_CACHE_PATH': 'C:\\Users\\LG\\AppData\\Roaming\\Code\\CachedData\\0870c2a0c7c0564e7631bfed2675573a94ba4455',
        'VSCODE_CRASH_REPORTER_PROCESS_TYPE': 'extensionHost',
        'VSCODE_CWD': 'C:\\WINDOWS\\System32',
        'VSCODE_ESM_ENTRYPOINT': 'vs/workbench/api/node/extensionHostProcess',
        'VSCODE_HANDLES_UNCAUGHT_ERRORS': 'true',
        'VSCODE_IPC_HOOK': '\\\\.\\pipe\\26ea775e-1.110.0-main-sock',
        'VSCODE_L10N_BUNDLE_LOCATION': '',
        'VSCODE_NLS_CONFIG': '{"userLocale":"en-us","osLocale":"ko","resolvedLanguage":"en","defaultMessagesFile":"C:\\\\Users\\\\LG\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code\\\\0870c2a0c7\\\\resources\\\\app\\\\out\\\\nls.messages.json","locale":"en-us","availableLanguages":{}}',
        'VSCODE_PID': '17176',
        'WINDIR': 'C:\\WINDOWS',
        'ZES_ENABLE_SYSMAN': '1',
        '_OLD_VIRTUAL_PATH': 'C:\\Users\\LG\\AppData\\Local\\Programs\\Microsoft VS Code;C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\util;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\NetSarang\\Xshell 8\\;C:\\Program Files (x86)\\NetSarang\\Xshell 7\\;C:\\Program Files\\Bandizip\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Git\\cmd;C:\\Users\\LG\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\;C:\\Users\\LG\\AppData\\Local\\Programs\\Python\\Python311\\;C:\\Users\\LG\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\LG\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;',
        '_OLD_VIRTUAL_PROMPT': '$P$G',
        'PYDEVD_USE_FRAME_EVAL': 'NO',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'FORCE_COLOR': '1',
        'CLICOLOR_FORCE': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://matplotlib_inline.backend_inline'}

In [140]:
os.getcwd()

'c:\\python_proj'

In [141]:
os.mkdir('test')

In [142]:
os.rmdir('test')

In [143]:
import json

In [147]:
with open('data.json', 'r', encoding='utf8') as f :
    # str -> dict
    data = json.load(f)

In [148]:
print(data, type(data))

[{'name': 'COOL', 'age': 25}] <class 'list'>

In [149]:
# list -> json(str)
json_str_data = json.dumps(data)
print(json_str_data, type(json_str_data))

[{"name": "COOL", "age": 25}] <class 'str'>

외부모듈

In [ ]:
# 외부모듈 설치 : !pip
!pip install pandas

In [ ]:
pip install numpy

In [154]:
import numpy as np

In [155]:
# ndarray : 넘파이 배열 생성
arr = np.array([1,2,3,4,5])

In [157]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>

In [158]:
arr + 10

array([11, 12, 13, 14, 15])

In [159]:
# 배열 생성
# 각 요소의 값을 0으로 채워서 생성
# 배열의 사이즈를 설정
# 사이즈의 정의 : 2차원 형식으로 행과, 열을 정의해서 생성
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]

In [160]:
# 1로 채운 배열
ones = np.ones((5,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [161]:
# 일련번호로 생성
# 0~10 사이의 숫자를 2칸씩 간격으로 생성
seq1 = np.arange(0, 11, 2)
print(seq1)

[ 0  2  4  6  8 10]

In [163]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 시작, 끝 , 몇개
# 1~10, 4
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]

In [164]:
# 2. 배열의 속성 확인
list_temp = [
    [1,2,3],
    [4,5,6]
]
arr1 = np.array(list_temp)

In [169]:
print(arr1)
print(arr1.shape)   # 배열의 사이즈 : (행, 열) => (2,3)
print(arr1.ndim)    # 배열의 차원 => 2
print(arr1.size)    # 배열의 요소 개수 => 6
print(arr1.dtype)   # 요소의 타입 => int64

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64

In [170]:
# 3. 배열의 인덱싱 : list와 동일
arr = np.array([10, 20, 30, 40])

In [173]:
print(arr[0])
#print(arr[4])
print(arr[-1])

10
40

In [178]:
print(arr1)
print(arr1[0], type(arr1[0]))
print(arr1[1][2])

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
6

In [181]:
arr = np.array([10, 20, 30, 40, 50])

In [185]:
# 슬라이싱
print(arr[:])
print(arr[1:4])
print(arr[1:9])
print(arr[1:])
print(arr[:4])

[10 20 30 40 50]
[20 30 40]
[20 30 40 50]
[20 30 40 50]
[10 20 30 40]

In [186]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [187]:
print(arr[:2 , 1: ])

[[2 3]
 [5 6]]

In [ ]:
# 5. 배열의 연산 : +, * , **
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [193]:
print(arr1 + 10)
print(arr1 + arr2)
print(arr1 * arr2)
print(arr2**2)

[11 12 13]
[5 7 9]
[ 4 10 18]
[16 25 36]

In [194]:
# 6. 배열의 구조 변환 : 1->2, 2->1
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)

In [196]:
# 1차원 -> 2차원
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr, reshaped_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)

In [197]:
# 2차원 -> 1차원
flated_arr = reshaped_arr.flatten()
print(flated_arr)

[1 2 3 4 5 6]

In [198]:
# 필터링
arr = np.array([1,2,3,4,5,6])
filtered_arr = arr[arr>3]
print(filtered_arr)

[4 5 6]

In [212]:
# 7. 난수 생성해서 배열을 생성
ran_arr1 = np.random.rand(10)
print(ran_arr1)

[0.41686961 0.88700038 0.66964335 0.4968973  0.81577751 0.46396531
 0.53821715 0.37818628 0.42447586 0.6121205 ]

In [233]:
ran_arr2 = np.random.randint(1, 45, size=(5,6))
print(ran_arr2)

[[ 9 13 22 42 41 14]
 [29 34  4  4 18  9]
 [11 36 24 10 27  8]
 [ 9  4 25  3 40 21]
 [22 28 13 25  1 37]]

In [234]:
import pandas as pd

In [235]:
# DataFrame 생성 : 2차원 형식의 표 모양으로 데이터 구조 생성
# dict => 'key' : [] 
# key=>열이름, [] 각 행의 데이터들
data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30, 25]
}
df = pd.DataFrame(data)

In [238]:
print(df,type(df))

   name  age
0  cool   20
1   hot   30
2  king   25 <class 'pandas.DataFrame'>

In [243]:
df.head(2)

   name  age
0  cool   20
1   hot   30

In [246]:
df.tail()

   name  age
0  cool   20
1   hot   30
2  king   25

In [247]:
# 데이터 구조 확인
df.shape

(3, 2)

In [248]:
# 데이터의 요약 정보
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [249]:
# 기초 통계 지표 ( 숫자 )
df.describe()

        age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [255]:
# 합, 평균
print(df['age'])
print(df['age'] < 30)
print(df[ df['age']<30 ])
print(df['age'].sum())
print(df['age'].mean())

0    20
1    30
2    25
Name: age, dtype: int64
0     True
1    False
2     True
Name: age, dtype: bool
   name  age
0  cool   20
2  king   25
75
25.0

In [256]:
data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30, 25],
    'score' : [90, 70, 60]
}
df = pd.DataFrame(data)

In [257]:
df

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   25     60

In [261]:
df[['name', 'age']]

   name  age
0  cool   20
1   hot   30
2  king   25

In [262]:
df

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   25     60

In [263]:
df['passed'] = df['score'] >= 70

In [264]:
df

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     60   False

In [265]:
df[['name', 'passed']]

   name  passed
0  cool    True
1   hot    True
2  king   False

In [ ]:
# 새로운 행 추가 : df.concat()
new_row = {
    'name' : ['SON'],
    'age' : [30],
    'score' : [55],
    'passed' : [False]
}
df2 = pd.DataFrame(new_row)

In [268]:
print(df)
print(df2)

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     60   False
  name  age  score  passed
0  SON   30     55   False

In [269]:
df3 = pd.concat([df, df2], ignore_index=True)
print(df3)

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     60   False
3   SON   30     55   False

In [272]:
# 특정 위치의 값을 변경
df3.loc[0, 'score'] = 85

In [273]:
df3

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60   False
3   SON   30     55   False

In [275]:
df3['passed'] = df3['score'] >= 60

In [276]:
df3

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60    True
3   SON   30     55   False

In [277]:
df3.loc[1, 'score'] = None

In [278]:
df3

   name  age  score  passed
0  cool   20   85.0    True
1   hot   30    NaN    True
2  king   25   60.0    True
3   SON   30   55.0   False

In [280]:
#df3.info()
df3.describe()

             age      score
count   4.000000   3.000000
mean   26.250000  66.666667
std     4.787136  16.072751
min    20.000000  55.000000
25%    23.750000  57.500000
50%    27.500000  60.000000
75%    30.000000  72.500000
max    30.000000  85.000000

In [282]:
df3.isnull()

    name    age  score  passed
0  False  False  False   False
1  False  False   True   False
2  False  False  False   False
3  False  False  False   False

In [284]:
df3

   name  age  score  passed
0  cool   20   85.0    True
1   hot   30    NaN    True
2  king   25   60.0    True
3   SON   30   55.0   False

In [285]:
# 결측치에 기본값을 저장
df3['score'] = df3['score'].fillna(100)

In [286]:
df3

   name  age  score  passed
0  cool   20   85.0    True
1   hot   30  100.0    True
2  king   25   60.0    True
3   SON   30   55.0   False

In [287]:
df3.loc[1, 'score'] = None

In [288]:
df3

   name  age  score  passed
0  cool   20   85.0    True
1   hot   30    NaN    True
2  king   25   60.0    True
3   SON   30   55.0   False

In [290]:
# 결측치의 행 삭제
df3 = df3.dropna()

In [291]:
df3

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True
2  king   25     60    True

In [294]:
# 정렬
sorted_df = df3.sort_values(by='score', ascending=False)
top_2 = sorted_df.head(2)

In [295]:
top_2

   name  age  score  passed
0  cool   20     85    True
1   hot   30     70    True

In [296]:
# 그룹핑 : ~ 별 => groupby()
data = {
    'team' : ['A', 'A', 'B', 'B', 'A'],
    'score' : [80, 90, 70, 80, 70]
}
df = pd.DataFrame(data)
df

  team  score
0    A     80
1    A     90
2    B     70
3    B     80
4    A     70

In [300]:
grouped_data = df.groupby('team')['score'].mean()

In [301]:
print(grouped_data)

team
A    80.0
B    75.0
Name: score, dtype: float64

In [306]:
grouped_data.to_csv('output1.csv', index=False)

In [304]:
data_csv = pd.read_csv('output.csv')

In [305]:
print(data_csv)
print(type(data_csv))

  team  score
0    A    180
1    A    190
2    B    170
3    B     10
4    A    170
<class 'pandas.DataFrame'>